name: Windows Server 2022

on:
  pull_request:
    types: [synchronize, opened]

env:
  OPENCV_VERSION: 4.5.5

jobs:
  build:

    strategy:
      matrix:
        platform: ["win", "uwp"]
        arch: ["x86", "x64", "ARM"]
        exclude:
          - platform: win
            arch: ARM

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install Server-Media-Foundation
        shell: powershell
        run: |
          Install-WindowsFeature Server-Media-Foundation

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build OpenCV
        shell: powershell
        run: |
          if ("${{matrix.platform}}" -eq 'win'){
            . ".\build_windows.ps1"
            BuildForWindows ${{matrix.arch}} "${env:VCPKG_ROOT}" $TRUE
          }
          elseif ("${{matrix.platform}}" -eq 'uwp'){
            . ".\build_uwp.ps1"
            BuildForUWP ${{matrix.arch}} "${env:VCPKG_ROOT}" $TRUE
          }

      - name: Set Version Variable
        id: version
        shell: powershell
        run: |
          $v = ${env:OPENCV_VERSION}.Replace(".", "")
          echo "::set-output name=OPENCV_VERSION_MOD::${v}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: opencv${{steps.version.outputs.OPENCV_VERSION_MOD}}_${{matrix.platform}}_${{matrix.arch}}
          path: build_${{matrix.platform}}_${{matrix.arch}}/install
